{% set name = "cellpose" %}
{% set version = "4.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cellpose-{{ version }}.tar.gz
  sha256: ebb8f74a89f63c63b5673b4f11b3734644a44b335286b0182f5508ad4b271e08

build:
  entry_points:
    - cellpose = cellpose.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - segment-anything  # Note: The conda-forge package is based on the PyPI 'segment-anything-py', not 'segment-anything'
    - fastremap
    - fill-voids
    - imagecodecs
    - llvmlite
    - matplotlib-base  # Imported but not declared as a dependency
    - natsort
    - numba >=0.53.0
    - numpy >=1.20.0
    - opencv
    - python >={{ python_min }}
    - scipy
    - tifffile
    - pytorch >=1.6
    - roifile
    - scikit-image    # Imported but not declared as a dependency
    - tqdm
    # GUI Dependencies
    - pyside6
    - pyqtgraph >=0.11.0rc0
    - qtpy
    - superqt
    # Distributed Dependencies
    - dask-core
    - dask-image
    - scikit-learn

test:
  imports:
    - cellpose
    - cellpose.core
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
    - cellpose --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/cellpose
  summary: anatomical segmentation algorithm
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/MouseLand/cellpose

extra:
  recipe-maintainers:
    - goanpeca
    - carsen-stringer
    - mrariden
    - stuarteberg
