{% set name = "cellpose" %}
{% set version = "3.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cellpose-{{ version }}.tar.gz
  sha256: 02ea4fd752b89bf23393d17a1c55a16de45dd162e77604613789f7fe3d8a84b3

build:
  entry_points:
    - cellpose = cellpose.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - setuptools
    - setuptools-scm
  run:
    - fastremap
    - imagecodecs
    - llvmlite
    - matplotlib-base  # Imported but not declared as a dependency
    - natsort
    - numba >=0.53.0
    - numpy >=1.20.0
    - opencv
    - python >=3.6
    - scipy
    - tifffile
    - pytorch >=1.6
    - roifile
    - scikit-image    # Imported but not declared as a dependency
    - tqdm
    # GUI Dependencies
    - pyqtgraph >=0.11.0rc0
    - qtpy
    - superqt
    # Distributed Dependencies
    - dask-core
    - dask-image
    - scikit-learn

test:
  imports:
    - cellpose
    - cellpose.core
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
    - cellpose --help
  requires:
    - pip

about:
  home: https://pypi.org/project/cellpose
  summary: anatomical segmentation algorithm
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/MouseLand/cellpose

extra:
  recipe-maintainers:
    - goanpeca
    - carsen-stringer
