{% set name = "cellpose" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cellpose-{{ version }}.tar.gz
  sha256: 7ff63cb60a154ce3c0a17ff05ed27d2aaaa1a24a4c7a8160c0a4c15443366618

build:
  entry_points:
    - cellpose = cellpose.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - setuptools
    - setuptools-scm
  run:
    - fastremap
    - imagecodecs
    - llvmlite
    - natsort
    - numba >=0.53.0
    - numpy >=1.20.0
    - opencv
    - python >=3.6
    - scipy
    - tifffile
    - pytorch >=1.6
    - roifile
    - tqdm
    # GUI Dependencies
    - google-cloud-storage
    - pyqtgraph >=0.11.0rc0
    - qtpy
    - superqt

test:
  imports:
    - cellpose
    - cellpose.core
  commands:
    - pip list
    - pip check
    - cellpose --help
  requires:
    - pip

about:
  home: https://pypi.org/project/cellpose
  summary: anatomical segmentation algorithm
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/MouseLand/cellpose

extra:
  recipe-maintainers:
    - goanpeca
